version: '3.8'

services:
  backend:
    # ghcr.io에서 이미지를 가져옵니다.
    # 이미지 경로를 소문자로 변경합니다. (ralph-hong)
    image: ghcr.io/hong-ralph/uscola/backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL} # 환경 변수에서 주입
    restart: unless-stopped
    networks:
      - uscola-network

  frontend:
    # ghcr.io에서 이미지를 가져옵니다.
    # 이미지 경로를 소문자로 변경합니다. (ralph-hong)
    image: ghcr.io/hong-ralph/uscola/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - uscola-network

networks:
  uscola-network:
    driver: bridge
