version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: uscola-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - uscola-network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    container_name: uscola-frontend
    restart: unless-stopped
    ports:
      # - "80:80"
      # - "443:443"
      - "4000:4000"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl/certs:ro  # SSL 인증서용 (선택사항)
    networks:
      - uscola-network

networks:
  uscola-network:
    driver: bridge